name: private-action
description: 'Pulls a private action into the current workspace'
inputs:
  repo-token:
    description: 'Token with read access to repo containing action'
    required: true
  repo-name:
    description: 'The organization/user and repo where action is stored'
    required: true
  repo-branch:
    description: 'The branch to pull private action from. Defaults to master'
    required: false
    default: master
runs:
  using: 'node12'
  main: 'dist/index.js'
