name: private-action
description: 'Pulls a private action into the current workspace'
inputs:
  github-token:
    description: 'Token with read access to repo containing action'
    required: true
  github-repo:
    description: 'The organization/user and  repo where action is stored'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
